#!/usr/bin/env node
// Example Workbench (v2.3 late integration with room brain, 2026-08-27) - the
// one-command demo.
// Prints the annotated map of this room: every control file and support
// location, the truth it owns, and why that truth is kept apart from the rest.
// `tests/tour.test.mjs` asserts every path here exists and every control this
// generation prescribes is described, so the map cannot drift from the room.

import { fileURLToPath } from 'node:url';
import { dirname } from 'node:path';

export const GENERATION = 'v2.3 late integration with room brain, 2026-08-27';
export const ROOM_ROOT = dirname(fileURLToPath(import.meta.url));

// Controls this generation prescribes for a filled room (README -> How To Use
// It, GENESIS Phase 6-7, templates/Wiki/README.md). The test requires each one.
export const PRESCRIBED = [
  'AGENTS.md', 'BLUEPRINT.md', 'LEXICON.md', 'TASKBOARD.md', 'RUNBOOK.md', 'README.md',
  'MEMORY.md', 'WORKBENCH_FEEDBACK.md', 'CLAUDE.md', '.claude/settings.json',
  'specs/S-001-self-explaining-room/SPEC.md',
];

export const PLACES = [
  { path: 'AGENTS.md',
    owns: 'How agents work here: authority order, read and edit scope, the spec-driven work loop, verification, documentation ownership, and Git rules.',
    why: 'It is the only always-loaded file. Product detail, definitions, work packets, and commands all load on demand from their own owners, so this file can stay short and be entirely about behavior.' },
  { path: 'BLUEPRINT.md',
    owns: 'The compact product map, cross-cutting architecture and invariants, non-goals, and the generated spec catalog.',
    why: 'Product direction is stable while work churns. The catalog between its markers is rendered from spec metadata, so completed history stays linked without ever being loaded for normal task selection.' },
  { path: 'LEXICON.md',
    owns: 'Accepted project-wide terms and their definitions, with the distinctions that keep two readers from using one word two ways.',
    why: 'Definitions only, read on demand when project language is ambiguous. Requirements and decisions stay in the Blueprint or the owning spec, so a meaning can be settled without reopening a decision.' },
  { path: 'TASKBOARD.md',
    owns: 'The hot projection of active specs only: current slice, owner, blocker, latest event, and next gate, plus any owner decision blocking a spec.',
    why: 'It is regenerated by `render` from spec metadata and completed specs disappear from it immediately. Deriving hot state instead of authoring it is what stops the board from disagreeing with the specs.' },
  { path: 'RUNBOOK.md',
    owns: 'Setup, run, test, evaluation, version-control, harness-upgrade, troubleshooting, and recovery procedures.',
    why: 'It has to be boring, exact, and executable: every command listed was run and seen to pass. Procedures go stale fastest, so they are kept apart from the prose that would hide a dead command.' },
  { path: 'README.md',
    owns: 'Orientation for a person arriving at the room: what it is, the two commands, and where each control lives.',
    why: 'Every other file is written for an agent operating under a contract. One door is for people, and it points at the control surfaces instead of restating them.' },
  { path: 'MEMORY.md',
    owns: 'The room brain: a wikilink router to the live controls, the durable notes beside it, and the up-link to a deployment wiki.',
    why: 'This generation added it because a room is not bootstrapped without a brain. It routes and never duplicates live task state; live controls outrank it when they disagree, and the stale note gets fixed.' },
  { path: 'WORKBENCH_FEEDBACK.md',
    owns: 'The append-only return channel to the harness: where its rules were unclear, wrong, or slow, with a proposed change and a status.',
    why: 'A problem with the harness rules is not one of this room\'s own tasks, so it gets its own log instead of the Taskboard. Lessons flow upstream and are validated in evals before anything is called better.' },
  { path: 'CLAUDE.md',
    owns: 'The Claude Code bridge: the single line `@AGENTS.md`.',
    why: 'One rule set, two readers. If the bridge carried rules of its own they would drift from AGENTS.md, so it carries none.' },
  { path: '.claude/settings.json',
    owns: 'The edit scope from AGENTS.md as machine-enforced permissions: deny secrets, allow the writable roots, ask on review-required actions. `.claude/README.md` beside it explains the mapping.',
    why: 'AGENTS.md describes the fence in prose, on the honor system. This file is the belt to those suspenders: deny beats allow, so the secret rules hold even under a broad allow glob.' },
  { path: 'specs',
    owns: 'Stable capability work packets, one folder per spec, at paths that never move between status folders.',
    why: 'A spec is a durable capability; a ticket inside it is a temporary slice. A stable path means every link to the record, and every evidence row in it, stays valid after the spec completes.' },
  { path: 'specs/S-001-self-explaining-room/SPEC.md',
    owns: 'The one capability this room has: requirements, decisions, tracer-bullet slices, acceptance, verification, append-only evidence, and completion.',
    why: 'Detailed truth lives here rather than in the Blueprint or Taskboard so normal work loads exactly one packet. Its slices each cross the whole stack, so any one of them is demoable on its own.' },
  { path: 'tour.mjs',
    owns: 'This room\'s one-command demo: the map you are reading, and the list of controls the generation prescribes.',
    why: 'Every milestone owes a demo artifact checkable in under a minute. This room\'s product is its own explanation, so the demo is the explanation printing itself.' },
  { path: 'tests/tour.test.mjs',
    owns: 'The proof that the map still matches the room.',
    why: 'It fails if a named path is missing, if a root document or prescribed control goes undescribed, or if an entry stops saying what it owns and why. That is the difference between documentation and a promise.' },
];

function wrap(label, text, width = 78) {
  const head = `    ${label.padEnd(6)}`;
  const hang = ' '.repeat(head.length);
  const out = [];
  let line = '';
  for (const word of text.split(/\s+/)) {
    if (line && (hang + line + ' ' + word).length > width) { out.push((out.length ? hang : head) + line); line = word; }
    else line = line ? `${line} ${word}` : word;
  }
  if (line) out.push((out.length ? hang : head) + line);
  return out;
}

export function render() {
  const lines = ['', `Example Workbench (${GENERATION}) - room map`, ''];
  for (const place of PLACES) lines.push(`  ${place.path}`, ...wrap('owns', place.owns), ...wrap('why', place.why), '');
  lines.push('  Run `node tests/tour.test.mjs` to check this map against the room itself.', '');
  return lines.join('\n');
}

if (process.argv[1] && process.argv[1].endsWith('tour.mjs')) process.stdout.write(render());
