#!/usr/bin/env node
// The Workbench Template's optional orientation demo: print the annotated map of a room.
//
// Every entry below names a real path in this room and says what truth it owns
// and why that truth is kept apart from every other. `tests/tour.test.mjs`
// asserts that each path exists and that every lane and collection the manifest
// declares appears here, so the map cannot quietly drift from the room.

import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

export const ROOM_ROOT = dirname(fileURLToPath(import.meta.url));

export function readManifest(root = ROOM_ROOT) {
  return JSON.parse(readFileSync(join(root, 'workbench/manifest.json'), 'utf8'));
}

// zone: which part of the room. lane/collection: the manifest key this place
// realizes, when it realizes one. owns: the truth kept here. why: the reason it
// is not kept somewhere else.
export const PLACES = [
  {
    zone: 'Root controls',
    path: 'AGENTS.md',
    owns: 'How agents work here: authority order, read and edit scope, the work loop, verification, and Git rules.',
    why: 'An agent arriving cold has to know what it may do before it reads anything about what to build. This is the only file that is always loaded, so no task can begin outside its fences.',
  },
  {
    zone: 'Root controls',
    path: 'BLUEPRINT.md',
    owns: 'The desired finished product: destination, people, outcomes, experience, design, constraints, lifecycle and non-goals.',
    why: 'Product direction changes far more slowly than task state. Keeping it separate means a spec can complete, or a ticket be abandoned, without editing the description of the product.',
  },
  {
    zone: 'Root controls',
    path: 'LEXICON.md',
    owns: 'The accepted meaning of every shared project term.',
    why: 'Two agents using one word for two things is the cheapest way to produce contradictory work. Definitions get one address so a disagreement about meaning has somewhere to be resolved.',
  },
  {
    zone: 'Root controls',
    path: 'RUNBOOK.md',
    owns: 'The commands: setup, run, test, verify, recover, upgrade.',
    why: 'Procedures are the truth most likely to go stale and the easiest to check. Kept apart from prose so that every line is a command someone actually ran and saw pass.',
  },
  {
    zone: 'Root controls',
    path: 'TASKBOARD.md',
    owns: 'A generated projection of active work: current slice, owner, blocker, latest event, next gate.',
    why: 'It is regenerated by `render` and never hand-edited. Deriving hot state instead of authoring it is what stops the board from disagreeing with the specs it summarizes.',
  },
  {
    zone: 'Root controls',
    path: 'README.md',
    owns: 'Orientation for a human arriving at the repository.',
    why: 'Everything else here is written for an agent operating under a contract. One door is for people.',
  },
  {
    zone: 'Root controls',
    path: 'CLAUDE.md',
    owns: 'The Claude Code bridge. Exactly `@AGENTS.md`, and nothing else.',
    why: 'One rule set, two readers. If the bridge carried rules of its own they would drift from AGENTS.md, so the readiness gate rejects any other content.',
  },

  {
    zone: 'The support root',
    path: 'workbench/manifest.json',
    owns: 'The declaration of this room: schema version, harness version, provenance, lane and collection paths, wiki profile, skill policy, and the git branches.',
    why: 'Every tool resolves paths through the manifest instead of hardcoding them. A room can therefore move a lane without a code change, and a tool can refuse to run in a room whose shape it does not understand.',
  },
  {
    zone: 'The support root',
    lane: 'specs',
    path: 'workbench/specs',
    owns: 'Capability truth: requirements, decisions, acceptance criteria, append-only evidence, and the completion result.',
    why: 'A spec is durable; a ticket inside it is temporary. Keeping the record with the capability rather than in a tracker means the reason a thing is the way it is outlives the sprint that made it.',
  },
  {
    zone: 'The support root',
    lane: 'docs',
    path: 'workbench/docs',
    owns: 'Long-form supporting documentation that is neither a root control nor a capability spec.',
    why: 'The root is capped at seven controls on purpose. Material that would bloat one of them lands here instead of being wedged into a file whose job is something else.',
  },
  {
    zone: 'The support root',
    collection: 'adr',
    path: 'workbench/docs/adr',
    owns: 'Accepted active architectural decisions, rationale, alternatives and supersession, with retired records accessible through history.',
    why: 'A decision and the code implementing it have different lifetimes. The ADR keeps the argument after the code changes, and records what was rejected so it is not re-litigated every time someone new arrives.',
  },
  {
    zone: 'The support root',
    lane: 'wiki',
    path: 'workbench/wiki',
    owns: 'The room brain: durable knowledge routed by `MEMORY.md` under the rules in `SCHEMA.md`.',
    why: 'Some knowledge belongs to the room but to no single capability. It lives here rather than being copied into several specs, and it never holds live task state.',
  },
  {
    zone: 'The support root',
    collection: 'design-concepts',
    path: 'workbench/wiki/design-concepts',
    owns: 'Owner-directed articles about how a design is meant to work.',
    why: 'Design intent is the first thing lost when only the implementation is written down. These are commissioned deliberately, not accumulated.',
  },
  {
    zone: 'The support root',
    collection: 'guidebooks',
    path: 'workbench/wiki/guidebooks',
    owns: 'How-to knowledge that outlives any one task.',
    why: 'A procedure that is useful twice belongs somewhere findable. It is not the Runbook, which is reserved for this project’s own verified commands.',
  },
  {
    zone: 'The support root',
    collection: 'archive',
    path: 'workbench/wiki/archive',
    owns: 'Superseded notes, kept for provenance.',
    why: 'Deleting a wrong note destroys the record that anyone believed it. Archiving keeps the trail without leaving the mistake in the live brain.',
  },
  {
    zone: 'The support root',
    lane: 'sessions',
    path: 'workbench/sessions',
    owns: 'Session records: local JSON working notes, readable Markdown handoffs, frozen historical checkpoints and ignored recovery material.',
    why: 'Most session text is scratch, and some of it contains things that must never be committed. This lane exists so that durability is a deliberate act rather than the default.',
  },
  {
    zone: 'The support root',
    collection: 'grilling',
    path: 'workbench/sessions/grilling',
    owns: 'Live interview notepads while a decision is still being argued. Untracked.',
    why: 'A notepad is a working record, never evidence. Keeping it out of version control stops half-formed reasoning from being cited as a settled decision.',
  },
  {
    zone: 'The support root',
    collection: 'handoffs',
    path: 'workbench/sessions/handoffs',
    owns: 'Readable Markdown instructions for a requested, scope-preserving transfer to another context. Untracked.',
    why: 'A handoff is addressed to the next session, not to the repository. It goes stale within hours, so committing it would publish something that is wrong by the time anyone reads it.',
  },
  {
    zone: 'The support root',
    collection: 'checkpoints',
    path: 'workbench/sessions/checkpoints',
    owns: 'Frozen historical checkpoint records retained with their original evidence boundaries.',
    why: 'New supported claims go directly to their durable owner after privacy and validity checks. Existing checkpoints remain historical; new checkpoint copies are retired.',
  },
  {
    zone: 'The support root',
    collection: 'notepads',
    path: 'workbench/sessions/notepads',
    owns: 'Local JSON objective notes, original findings, corrections and the next executable action.',
    why: 'Unfinished reasoning needs recoverable context without becoming project authority. Live notes stay ignored; selected supported claims belong in their durable owner.',
  },
  {
    zone: 'The support root',
    collection: 'notepad-templates',
    path: 'workbench/sessions/notepads/templates',
    owns: 'Tracked generic JSON examples and the shared notepad schema.',
    why: 'Examples explain the interchange shape without publishing live notes. They are deliberately distinct from the ignored work and handoff records beside them.',
  },
  {
    zone: 'The support root',
    collection: 'recovery',
    path: 'workbench/sessions/recovery',
    owns: 'Ignored operational backups and optional private transport configuration.',
    why: 'A rollback needs original bytes and a checkable boundary. Recovery material stays local and does not become a permanent published handoff archive.',
  },
  {
    zone: 'The support root',
    lane: 'feedback',
    path: 'workbench/feedback',
    owns: 'The return channel to the harness these controls came from.',
    why: 'When a rule is wrong, the room needs somewhere to say so that is not the rule itself. It sits in a lane rather than at the root so the root keeps exactly seven controls.',
  },
  {
    zone: 'The support root',
    lane: 'tools',
    path: 'workbench/tools',
    owns: 'The harness runtime, installed as copies with a receipt (`.workbench-tools.json`) recording the source release, commit, and a hash per file.',
    why: 'The room runs its own copies, so it is not coupled to a checkout of the harness sitting elsewhere on disk. The receipt is what makes an upgrade checkable instead of hopeful — and it is why the lane changes only through an explicit update. A stray file here stops work selection until it is moved.',
  },

  {
    zone: 'The product',
    path: 'tour.mjs',
    owns: 'This room’s one-command demo: the map you are reading.',
    why: 'This optional orientation demonstrates the installed structure in under a minute. Future projects choose their own product and demo rather than inheriting a fictional Example application.',
  },
  {
    zone: 'The product',
    path: 'tests/tour.test.mjs',
    owns: 'The check that keeps the map honest.',
    why: 'It asserts every path named here exists, and that every lane and collection the manifest declares is explained. Add a lane without describing it and this test goes red — which is the difference between documentation and a promise.',
  },
];

// How this room came to exist, and how it reaches a newer harness version.
// Every fact here is read from the room — the manifest's provenance block and
// the tools receipt — so the account cannot drift from what the room actually
// records. Only the route itself is prose, and `tests/tour.test.mjs` checks
// that the commands it names exist in this room's own tools lane.
export function lifecycle(root = ROOM_ROOT) {
  const manifest = readManifest(root);
  const receiptPath = join(root, manifest.lanes.tools, '.workbench-tools.json');
  const receipt = JSON.parse(readFileSync(receiptPath, 'utf8'));
  return {
    how: manifest.provenance.lifecycle,
    source: manifest.provenance.source,
    stamped: manifest.workbenchVersion,
    attests: {
      release: receipt.source.release,
      commit: receipt.source.commit,
      files: Object.keys(receipt.files).length,
    },
    route: ROUTE,
  };
}

// The maintenance route for a room already on v3. Stated carefully because the
// obvious guess is wrong: `workbench-upgrade.mjs upgrade` is the one-time v2 to
// v3 migration and refuses a room that already has a support root.
export const ROUTE = [
  {
    step: 'Check the tools lane first',
    detail: 'List `workbench/tools/` and compare it against the receipt. A file the managed runtime does not ship makes `next` and `claim` refuse with exit 1 after the update, and work selection stops until it is moved out.',
  },
  {
    step: 'Migrate supported layout additions',
    detail: 'From the clean release checkout: `workbench-layout.mjs migrate --project PATH --version vX.Y.Z`. This preserves existing content and adds declared notepad/recovery collections and a stable room identity when missing.',
  },
  {
    step: 'Update the managed runtime',
    detail: 'From a clean release checkout: `workbench-tools.mjs update --project PATH --home EXISTING_HOME --explicit-update`. The existing home owns the backup. It backs up the old lane and rewrites the receipt.',
  },
  {
    step: 'Preserve historical source identity',
    detail: 'Keep the original genesis/adoption `provenance.source`. The tools receipt and layout provenance name the new installed components; a version update does not change where this room began.',
  },
  {
    step: 'Stamp the room’s version by hand',
    detail: 'Set `workbenchVersion` in `workbench/manifest.json`. No command does this, and until it is done `doctor` reports `unverified-provenance` as attention.',
  },
  {
    step: 'Re-stamp the documents that name a version',
    detail: 'The seeded wiki documents and the root controls each carry a `Generated from LLM Workbench vX.Y.Z` line. `seed-documents` refreshes lane documents only, so these are a hand edit; `doctor` reports the wiki ones as `stale-stamp` and does not check the root controls at all.',
  },
];

const ZONE_BLURBS = {
  'Root controls':
    'Seven files, always at the root, always the same seven. An agent reads these\n  on entry and nothing else is required to know how to behave here.',
  'The support root':
    'Everything the harness manages lives under `workbench/`, declared by a manifest\n  rather than assumed by path. This is what makes a room portable and upgradable.',
  'The product':
    'What this room actually builds. Every room has one; here it happens to be an\n  explanation of rooms.',
};

function render(manifest) {
  const lines = [];
  const name = manifest.name || 'Workbench Template';
  lines.push('');
  lines.push(`  ${name} — what a workbench is, and why each part is where it is`);
  lines.push(`  harness ${manifest.workbenchVersion}  ·  schema ${manifest.schemaVersion}  ·  provenance ${manifest.provenance.lifecycle}`);
  lines.push('');

  for (const zone of ['Root controls', 'The support root', 'The product']) {
    lines.push(`── ${zone} ${'─'.repeat(Math.max(0, 68 - zone.length))}`);
    lines.push('');
    lines.push(`  ${ZONE_BLURBS[zone]}`);
    lines.push('');
    for (const place of PLACES.filter((p) => p.zone === zone)) {
      const tag = place.lane ? `  [lane: ${place.lane}]` : place.collection ? `  [collection: ${place.collection}]` : '';
      lines.push(`  ${place.path}${tag}`);
      lines.push(...field('owns', place.owns));
      lines.push(...field('why', place.why));
      lines.push('');
    }
  }
  lines.push('  Run `node tests/tour.test.mjs` to check this map against the room itself.');
  lines.push('');
  return lines.join('\n');
}

// A labelled paragraph with a hanging indent, so continuation lines line up
// under the text rather than under the label.
function field(label, text, width = 78) {
  const head = `    ${label.padEnd(6)}`;
  const hang = ' '.repeat(head.length);
  const out = [];
  let line = '';
  for (const word of text.split(/\s+/)) {
    if (line && (hang + line + ' ' + word).length > width) {
      out.push((out.length ? hang : head) + line);
      line = word;
    } else {
      line = line ? `${line} ${word}` : word;
    }
  }
  if (line) out.push((out.length ? hang : head) + line);
  return out;
}

function renderLifecycle(l) {
  const lines = [''];
  lines.push('  How this room came to exist');
  lines.push('');
  lines.push(`    lifecycle   ${l.how}`);
  lines.push(`    created from ${l.source.repository}`);
  lines.push(`    release     ${l.source.release} at ${l.source.commit}`);
  lines.push(`    stamped     ${l.stamped}`);
  lines.push('');
  lines.push(`  The tools receipt attests ${l.attests.files} managed files from release`);
  lines.push(`  ${l.attests.release} at ${l.attests.commit}. That receipt is what makes an`);
  lines.push('  upgrade checkable instead of hopeful.');
  lines.push('');
  lines.push('  Reaching a newer harness version');
  lines.push('');
  lines.push('  `workbench-upgrade.mjs upgrade` is NOT this route — it is the one-time v2 to');
  lines.push('  v3 migration and refuses a room that already has a support root. For a room');
  lines.push('  already on v3 the route is:');
  lines.push('');
  l.route.forEach((r, i) => {
    lines.push(`  ${i + 1}. ${r.step}`);
    lines.push(...field('', r.detail));
    lines.push('');
  });
  return lines.join('\n');
}

if (process.argv[1] && process.argv[1].endsWith('tour.mjs')) {
  const manifest = readManifest();
  if (process.argv.includes('--json')) {
    process.stdout.write(JSON.stringify({ places: PLACES, lifecycle: lifecycle() }, null, 2) + '\n');
  } else if (process.argv.includes('--lifecycle')) {
    process.stdout.write(renderLifecycle(lifecycle()) + '\n');
  } else {
    process.stdout.write(render(manifest) + '\n');
  }
}
